<?php

namespace Database\Seeders;

use App\Models\CalibrationMaster;
use App\Models\CalibrationMasterImage;
use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CalibrationMasterDemoSeeder extends Seeder
{
    public function run(): void
    {
        DB::transaction(function () {
            CalibrationMasterImage::query()->delete();
            CalibrationMaster::query()->delete();

            foreach ($this->records() as $data) {
                $images = $data['images'] ?? [];
                unset($data['images']);

                $record = CalibrationMaster::query()->create($data);

                foreach ($images as $i => $img) {
                    $record->images()->create([
                        'sort_order' => $i + 1,
                        'file_name'  => basename($img),
                        'file_path'  => '/images/calibration-masters/' . basename($img),
                        'mime_type'  => 'image/jpeg',
                        'width'      => 0,
                        'height'     => 0,
                        'source_sheet_name' => null,
                        'source_row'        => null,
                        'source_col'        => null,
                        'metadata'          => [],
                    ]);
                }
            }
        });
    }

    private function records(): array
    {
        $today = Carbon::today();

        // Helpers
        $dueSoon = fn (int $days) => $today->copy()->addDays($days)->toDateString();
        $cal     = fn (int $daysBack, int $freqMonths) => [
            'last' => $today->copy()->subDays($daysBack)->toDateString(),
            'next' => $today->copy()->subDays($daysBack)->addMonths($freqMonths)->toDateString(),
        ];

        return [
            // ── DUE SOON (15 entries) ───────────────────────────────────────
            [
                'sheet_name'               => 'Demo',
                'sheet_order'              => 1,
                'source_row'               => 1,
                'reference_no'             => 'CAL-DS-001',
                'name_type'                => 'Vernier Caliper',
                'function'                 => 'Linear measurement of external and internal dimensions',
                'identification_number'    => 'VC-2023-001',
                'measurement_range'        => '0–150 mm',
                'inherent_accuracy'        => '±0.02 mm',
                'usage_accuracy'           => '±0.05 mm',
                'owner_location'           => 'QA Lab – Bay A',
                'frequency_label'          => 'Yearly',
                'frequency_interval_months'=> 12,
                'last_calibration_date'    => $cal(350, 12)['last'],
                'next_calibration_date'    => $dueSoon(15),
                'metadata'                 => [],
                'image'                    => '/images/calibration-masters/calibration_sheet1_r6_1.jpeg',
                'images'                   => ['calibration_sheet1_r6_1.jpeg', 'calibration_sheet1_r6_2.jpeg'],
            ],
            [
                'sheet_name'               => 'Demo',
                'sheet_order'              => 1,
                'source_row'               => 2,
                'reference_no'             => 'CAL-DS-002',
                'name_type'                => 'Micrometer (Outside)',
                'function'                 => 'Precision measurement of outer diameters',
                'identification_number'    => 'MIC-OUT-007',
                'measurement_range'        => '0–25 mm',
                'inherent_accuracy'        => '±0.001 mm',
                'usage_accuracy'           => '±0.005 mm',
                'owner_location'           => 'Production – Line 1',
                'frequency_label'          => '½ Yearly',
                'frequency_interval_months'=> 6,
                'last_calibration_date'    => $cal(175, 6)['last'],
                'next_calibration_date'    => $dueSoon(5),
                'metadata'                 => [],
                'image'                    => '/images/calibration-masters/calibration_sheet1_r7_3.jpeg',
                'images'                   => ['calibration_sheet1_r7_3.jpeg', 'calibration_sheet1_r7_4.jpeg'],
            ],
            [
                'sheet_name'               => 'Demo',
                'sheet_order'              => 1,
                'source_row'               => 3,
                'reference_no'             => 'CAL-DS-003',
                'name_type'                => 'Digital Torque Wrench',
                'function'                 => 'Controlled torque application and verification',
                'identification_number'    => 'TW-D-015',
                'measurement_range'        => '5–100 N·m',
                'inherent_accuracy'        => '±2%',
                'usage_accuracy'           => '±4%',
                'owner_location'           => 'Maintenance Workshop',
                'frequency_label'          => 'Yearly',
                'frequency_interval_months'=> 12,
                'last_calibration_date'    => $cal(358, 12)['last'],
                'next_calibration_date'    => $dueSoon(7),
                'metadata'                 => [],
                'image'                    => '/images/calibration-masters/calibration_sheet1_r9_9.jpeg',
                'images'                   => ['calibration_sheet1_r9_9.jpeg', 'calibration_sheet1_r9_10.jpeg'],
            ],
            [
                'sheet_name'               => 'Demo',
                'sheet_order'              => 1,
                'source_row'               => 4,
                'reference_no'             => 'CAL-DS-004',
                'name_type'                => 'Pressure Gauge',
                'function'                 => 'Hydraulic line pressure monitoring',
                'identification_number'    => 'PG-HYD-003',
                'measurement_range'        => '0–16 bar',
                'inherent_accuracy'        => '±0.5%',
                'usage_accuracy'           => '±1%',
                'owner_location'           => 'Utility Room',
                'frequency_label'          => 'Yearly',
                'frequency_interval_months'=> 12,
                'last_calibration_date'    => $cal(345, 12)['last'],
                'next_calibration_date'    => $dueSoon(20),
                'metadata'                 => [],
                'image'                    => '/images/calibration-masters/calibration_sheet1_r10_7.jpeg',
                'images'                   => ['calibration_sheet1_r10_7.jpeg', 'calibration_sheet1_r10_8.jpeg'],
            ],
            [
                'sheet_name'               => 'Demo',
                'sheet_order'              => 1,
                'source_row'               => 5,
                'reference_no'             => 'CAL-DS-005',
                'name_type'                => 'Thermometer (Digital)',
                'function'                 => 'Oven and process temperature verification',
                'identification_number'    => 'THERM-DIG-009',
                'measurement_range'        => '-50 to 300 °C',
                'inherent_accuracy'        => '±0.3 °C',
                'usage_accuracy'           => '±1 °C',
                'owner_location'           => 'QA Lab – Bay B',
                'frequency_label'          => '½ Yearly',
                'frequency_interval_months'=> 6,
                'last_calibration_date'    => $cal(170, 6)['last'],
                'next_calibration_date'    => $dueSoon(10),
                'metadata'                 => [],
                'image'                    => '/images/calibration-masters/calibration_sheet1_r11_5.jpeg',
                'images'                   => ['calibration_sheet1_r11_5.jpeg', 'calibration_sheet1_r11_6.jpeg'],
            ],
            [
                'sheet_name'               => 'Demo',
                'sheet_order'              => 1,
                'source_row'               => 6,
                'reference_no'             => 'CAL-DS-006',
                'name_type'                => 'Dial Gauge',
                'function'                 => 'Surface flatness and runout inspection',
                'identification_number'    => 'DG-FLAT-022',
                'measurement_range'        => '0–10 mm (0.01 resolution)',
                'inherent_accuracy'        => '±0.01 mm',
                'usage_accuracy'           => '±0.02 mm',
                'owner_location'           => 'Incoming Inspection',
                'frequency_label'          => 'Yearly',
                'frequency_interval_months'=> 12,
                'last_calibration_date'    => $cal(340, 12)['last'],
                'next_calibration_date'    => $dueSoon(25),
                'metadata'                 => [],
                'image'                    => '/images/calibration-masters/calibration_sheet1_r12_13.jpeg',
                'images'                   => ['calibration_sheet1_r12_13.jpeg', 'calibration_sheet1_r12_14.jpeg'],
            ],
            [
                'sheet_name'               => 'Demo',
                'sheet_order'              => 1,
                'source_row'               => 7,
                'reference_no'             => 'CAL-DS-007',
                'name_type'                => 'Digital Multimeter',
                'function'                 => 'Electrical parameter measurement (V, A, Ω)',
                'identification_number'    => 'DMM-ELEC-011',
                'measurement_range'        => 'AC/DC 0–1000 V',
                'inherent_accuracy'        => '±0.05%',
                'usage_accuracy'           => '±0.1%',
                'owner_location'           => 'Engineering Lab',
                'frequency_label'          => 'Yearly',
                'frequency_interval_months'=> 12,
                'last_calibration_date'    => $cal(355, 12)['last'],
                'next_calibration_date'    => $dueSoon(10),
                'metadata'                 => [],
                'image'                    => '/images/calibration-masters/calibration_sheet1_r13_15.jpeg',
                'images'                   => ['calibration_sheet1_r13_15.jpeg', 'calibration_sheet1_r13_16.jpeg'],
            ],
            [
                'sheet_name'               => 'Demo',
                'sheet_order'              => 2,
                'source_row'               => 1,
                'reference_no'             => 'CAL-DS-008',
                'name_type'                => 'Height Gauge',
                'function'                 => 'Vertical height measurement on surface plate',
                'identification_number'    => 'HG-SURF-005',
                'measurement_range'        => '0–300 mm',
                'inherent_accuracy'        => '±0.02 mm',
                'usage_accuracy'           => '±0.05 mm',
                'owner_location'           => 'QA Lab – Bay A',
                'frequency_label'          => 'Yearly',
                'frequency_interval_months'=> 12,
                'last_calibration_date'    => $cal(360, 12)['last'],
                'next_calibration_date'    => $dueSoon(5),
                'metadata'                 => [],
                'image'                    => '/images/calibration-masters/calibration_sheet2_r17_1.jpeg',
                'images'                   => ['calibration_sheet2_r17_1.jpeg', 'calibration_sheet2_r17_2.jpeg'],
            ],
            [
                'sheet_name'               => 'Demo',
                'sheet_order'              => 2,
                'source_row'               => 2,
                'reference_no'             => 'CAL-DS-009',
                'name_type'                => 'Force Gauge',
                'function'                 => 'Pull and push force measurement for assembly verification',
                'identification_number'    => 'FG-ASM-018',
                'measurement_range'        => '0–500 N',
                'inherent_accuracy'        => '±0.5 N',
                'usage_accuracy'           => '±1 N',
                'owner_location'           => 'Assembly – Line 2',
                'frequency_label'          => 'Yearly',
                'frequency_interval_months'=> 12,
                'last_calibration_date'    => $cal(352, 12)['last'],
                'next_calibration_date'    => $dueSoon(13),
                'metadata'                 => [],
                'image'                    => '/images/calibration-masters/calibration_sheet2_r6_16.jpeg',
                'images'                   => ['calibration_sheet2_r6_16.jpeg', 'calibration_sheet2_r6_17.jpeg'],
            ],
            [
                'sheet_name'               => 'Demo',
                'sheet_order'              => 2,
                'source_row'               => 3,
                'reference_no'             => 'CAL-DS-010',
                'name_type'                => 'pH Meter',
                'function'                 => 'Process solution acidity measurement',
                'identification_number'    => 'PHM-PROC-004',
                'measurement_range'        => '0–14 pH',
                'inherent_accuracy'        => '±0.01 pH',
                'usage_accuracy'           => '±0.05 pH',
                'owner_location'           => 'Chemical Lab',
                'frequency_label'          => 'Quarterly',
                'frequency_interval_months'=> 3,
                'last_calibration_date'    => $cal(88, 3)['last'],
                'next_calibration_date'    => $dueSoon(4),
                'metadata'                 => [],
                'image'                    => '/images/calibration-masters/calibration_sheet2_r7_18.jpeg',
                'images'                   => ['calibration_sheet2_r7_18.jpeg', 'calibration_sheet2_r7_19.jpeg'],
            ],
            [
                'sheet_name'               => 'Demo',
                'sheet_order'              => 3,
                'source_row'               => 1,
                'reference_no'             => 'CAL-DS-011',
                'name_type'                => 'Roughness Tester',
                'function'                 => 'Surface roughness (Ra) measurement',
                'identification_number'    => 'RT-SURF-002',
                'measurement_range'        => '0.01–160 µm Ra',
                'inherent_accuracy'        => '±5%',
                'usage_accuracy'           => '±10%',
                'owner_location'           => 'QA Lab – Bay C',
                'frequency_label'          => 'Yearly',
                'frequency_interval_months'=> 12,
                'last_calibration_date'    => $cal(348, 12)['last'],
                'next_calibration_date'    => $dueSoon(17),
                'metadata'                 => [],
                'image'                    => '/images/calibration-masters/calibration_sheet3_r8_1.jpeg',
                'images'                   => ['calibration_sheet3_r8_1.jpeg', 'calibration_sheet3_r8_2.jpeg'],
            ],
            [
                'sheet_name'               => 'Demo',
                'sheet_order'              => 3,
                'source_row'               => 2,
                'reference_no'             => 'CAL-DS-012',
                'name_type'                => 'Hardness Tester (Rockwell)',
                'function'                 => 'Material hardness verification on finished parts',
                'identification_number'    => 'HT-RCK-006',
                'measurement_range'        => 'HRC 20–70',
                'inherent_accuracy'        => '±0.5 HRC',
                'usage_accuracy'           => '±1 HRC',
                'owner_location'           => 'Metallurgy Lab',
                'frequency_label'          => '½ Yearly',
                'frequency_interval_months'=> 6,
                'last_calibration_date'    => $cal(165, 6)['last'],
                'next_calibration_date'    => $dueSoon(15),
                'metadata'                 => [],
                'image'                    => '/images/calibration-masters/calibration_sheet3_r9_7.jpeg',
                'images'                   => ['calibration_sheet3_r9_7.jpeg', 'calibration_sheet3_r9_8.jpeg'],
            ],
            [
                'sheet_name'               => 'Demo',
                'sheet_order'              => 3,
                'source_row'               => 3,
                'reference_no'             => 'CAL-DS-013',
                'name_type'                => 'Weighing Scale (Precision)',
                'function'                 => 'Batch weight and dosing verification',
                'identification_number'    => 'WS-PREC-030',
                'measurement_range'        => '0–5000 g (0.1 g resolution)',
                'inherent_accuracy'        => '±0.1 g',
                'usage_accuracy'           => '±0.5 g',
                'owner_location'           => 'Production – Weighing Room',
                'frequency_label'          => 'Quarterly',
                'frequency_interval_months'=> 3,
                'last_calibration_date'    => $cal(84, 3)['last'],
                'next_calibration_date'    => $dueSoon(8),
                'metadata'                 => [],
                'image'                    => '/images/calibration-masters/calibration_sheet3_r12_3.jpeg',
                'images'                   => ['calibration_sheet3_r12_3.jpeg', 'calibration_sheet3_r12_4.jpeg'],
            ],
            [
                'sheet_name'               => 'Demo',
                'sheet_order'              => 4,
                'source_row'               => 1,
                'reference_no'             => 'CAL-DS-014',
                'name_type'                => 'Clamp Meter',
                'function'                 => 'Non-contact AC current measurement',
                'identification_number'    => 'CM-AC-014',
                'measurement_range'        => '0–1000 A AC',
                'inherent_accuracy'        => '±1.5%',
                'usage_accuracy'           => '±2%',
                'owner_location'           => 'Engineering Lab',
                'frequency_label'          => 'Yearly',
                'frequency_interval_months'=> 12,
                'last_calibration_date'    => $cal(341, 12)['last'],
                'next_calibration_date'    => $dueSoon(24),
                'metadata'                 => [],
                'image'                    => '/images/calibration-masters/calibration_sheet-4_r7_2.jpeg',
                'images'                   => ['calibration_sheet-4_r7_2.jpeg', 'calibration_sheet-4_r7_3.jpeg'],
            ],
            [
                'sheet_name'               => 'Demo',
                'sheet_order'              => 4,
                'source_row'               => 2,
                'reference_no'             => 'CAL-DS-015',
                'name_type'                => 'Ultrasonic Thickness Gauge',
                'function'                 => 'Non-destructive wall thickness measurement',
                'identification_number'    => 'UTG-NDT-019',
                'measurement_range'        => '1–300 mm (steel)',
                'inherent_accuracy'        => '±0.1 mm',
                'usage_accuracy'           => '±0.2 mm',
                'owner_location'           => 'QC – NDT Bay',
                'frequency_label'          => 'Yearly',
                'frequency_interval_months'=> 12,
                'last_calibration_date'    => $cal(337, 12)['last'],
                'next_calibration_date'    => $dueSoon(28),
                'metadata'                 => [],
                'image'                    => '/images/calibration-masters/calibration_sheet-4_r10_8.jpeg',
                'images'                   => ['calibration_sheet-4_r10_8.jpeg', 'calibration_sheet-4_r10_9.jpeg'],
            ],

            // ── OUT FOR CALIBRATION (4 entries) ────────────────────────────
            [
                'sheet_name'               => 'Demo',
                'sheet_order'              => 1,
                'source_row'               => 20,
                'reference_no'             => 'CAL-OFC-001',
                'name_type'                => 'Coordinate Measuring Machine Probe',
                'function'                 => '3D coordinate measurement for precision parts',
                'identification_number'    => 'CMM-PROBE-001',
                'measurement_range'        => '0–600 mm (X/Y/Z)',
                'inherent_accuracy'        => '±0.003 mm',
                'usage_accuracy'           => '±0.005 mm',
                'owner_location'           => 'Metrology Room',
                'frequency_label'          => 'Yearly',
                'frequency_interval_months'=> 12,
                'last_calibration_date'    => $today->copy()->subDays(3)->toDateString(),
                'next_calibration_date'    => $today->copy()->addMonths(12)->toDateString(),
                'metadata'                 => [
                    'cal_status' => 'out_for_calibration',
                    'sent_to'    => 'SIRIM QAS International',
                ],
                'image'                    => '/images/calibration-masters/calibration_sheet1_r6_1.jpeg',
                'images'                   => ['calibration_sheet1_r6_1.jpeg'],
            ],
            [
                'sheet_name'               => 'Demo',
                'sheet_order'              => 2,
                'source_row'               => 20,
                'reference_no'             => 'CAL-OFC-002',
                'name_type'                => 'Lux Meter',
                'function'                 => 'Workplace illumination level verification',
                'identification_number'    => 'LUX-WORK-008',
                'measurement_range'        => '0–200,000 lux',
                'inherent_accuracy'        => '±3%',
                'usage_accuracy'           => '±5%',
                'owner_location'           => 'Safety Department',
                'frequency_label'          => 'Yearly',
                'frequency_interval_months'=> 12,
                'last_calibration_date'    => $today->copy()->subDays(5)->toDateString(),
                'next_calibration_date'    => $today->copy()->addMonths(12)->toDateString(),
                'metadata'                 => [
                    'cal_status' => 'out_for_calibration',
                    'sent_to'    => 'Bureau Veritas',
                ],
                'image'                    => '/images/calibration-masters/calibration_sheet2_r6_16.jpeg',
                'images'                   => ['calibration_sheet2_r6_16.jpeg'],
            ],
            [
                'sheet_name'               => 'Demo',
                'sheet_order'              => 3,
                'source_row'               => 20,
                'reference_no'             => 'CAL-OFC-003',
                'name_type'                => 'Sound Level Meter',
                'function'                 => 'Noise level monitoring for HSE compliance',
                'identification_number'    => 'SLM-HSE-013',
                'measurement_range'        => '30–130 dB(A)',
                'inherent_accuracy'        => '±1.5 dB',
                'usage_accuracy'           => '±2 dB',
                'owner_location'           => 'Safety Department',
                'frequency_label'          => 'Yearly',
                'frequency_interval_months'=> 12,
                'last_calibration_date'    => $today->copy()->subDays(7)->toDateString(),
                'next_calibration_date'    => $today->copy()->addMonths(12)->toDateString(),
                'metadata'                 => [
                    'cal_status' => 'out_for_calibration',
                    'sent_to'    => 'DOSH-accredited lab',
                ],
                'image'                    => '/images/calibration-masters/calibration_sheet3_r8_1.jpeg',
                'images'                   => ['calibration_sheet3_r8_1.jpeg'],
            ],
            [
                'sheet_name'               => 'Demo',
                'sheet_order'              => 4,
                'source_row'               => 20,
                'reference_no'             => 'CAL-OFC-004',
                'name_type'                => 'Vacuum Gauge',
                'function'                 => 'Vacuum line pressure monitoring in cleanroom',
                'identification_number'    => 'VG-CLEAN-025',
                'measurement_range'        => '-1 to 0 bar (gauge)',
                'inherent_accuracy'        => '±0.5%',
                'usage_accuracy'           => '±1%',
                'owner_location'           => 'Cleanroom – Level 2',
                'frequency_label'          => 'Yearly',
                'frequency_interval_months'=> 12,
                'last_calibration_date'    => $today->copy()->subDays(2)->toDateString(),
                'next_calibration_date'    => $today->copy()->addMonths(12)->toDateString(),
                'metadata'                 => [
                    'cal_status' => 'out_for_calibration',
                    'sent_to'    => 'TÜV SÜD',
                ],
                'image'                    => '/images/calibration-masters/calibration_sheet-4_r7_2.jpeg',
                'images'                   => ['calibration_sheet-4_r7_2.jpeg'],
            ],

            // ── CERT RECEIVED (3 entries) ───────────────────────────────────
            [
                'sheet_name'               => 'Demo',
                'sheet_order'              => 1,
                'source_row'               => 30,
                'reference_no'             => 'CAL-CR-001',
                'name_type'                => 'Tape Measure (Steel)',
                'function'                 => 'General linear measurement for layout and inspection',
                'identification_number'    => 'TM-STL-033',
                'measurement_range'        => '0–10 m',
                'inherent_accuracy'        => '±1 mm',
                'usage_accuracy'           => '±2 mm',
                'owner_location'           => 'Warehouse',
                'frequency_label'          => '2 Yearly',
                'frequency_interval_months'=> 24,
                'last_calibration_date'    => $today->copy()->subDays(2)->toDateString(),
                'next_calibration_date'    => $today->copy()->addMonths(24)->toDateString(),
                'metadata'                 => [
                    'cal_status' => 'cert_received',
                    'cert_no'    => 'SIRIM-2025-18827',
                ],
                'image'                    => '/images/calibration-masters/calibration_sheet1_r9_9.jpeg',
                'images'                   => ['calibration_sheet1_r9_9.jpeg', 'calibration_sheet1_r9_10.jpeg'],
            ],
            [
                'sheet_name'               => 'Demo',
                'sheet_order'              => 2,
                'source_row'               => 30,
                'reference_no'             => 'CAL-CR-002',
                'name_type'                => 'Infrared Thermometer',
                'function'                 => 'Non-contact surface temperature spot-check',
                'identification_number'    => 'IRT-NC-021',
                'measurement_range'        => '-50 to 550 °C',
                'inherent_accuracy'        => '±1.5 °C',
                'usage_accuracy'           => '±2 °C',
                'owner_location'           => 'Production – Line 3',
                'frequency_label'          => 'Yearly',
                'frequency_interval_months'=> 12,
                'last_calibration_date'    => $today->copy()->subDays(1)->toDateString(),
                'next_calibration_date'    => $today->copy()->addMonths(12)->toDateString(),
                'metadata'                 => [
                    'cal_status' => 'cert_received',
                    'cert_no'    => 'BV-2025-44012',
                ],
                'image'                    => '/images/calibration-masters/calibration_sheet2_r7_18.jpeg',
                'images'                   => ['calibration_sheet2_r7_18.jpeg', 'calibration_sheet2_r7_19.jpeg'],
            ],
            [
                'sheet_name'               => 'Demo',
                'sheet_order'              => 3,
                'source_row'               => 30,
                'reference_no'             => 'CAL-CR-003',
                'name_type'                => 'Anemometer',
                'function'                 => 'Air velocity measurement for HVAC and cleanroom qualification',
                'identification_number'    => 'ANEM-HVAC-010',
                'measurement_range'        => '0–30 m/s',
                'inherent_accuracy'        => '±0.1 m/s',
                'usage_accuracy'           => '±0.2 m/s',
                'owner_location'           => 'Facility Engineering',
                'frequency_label'          => 'Yearly',
                'frequency_interval_months'=> 12,
                'last_calibration_date'    => $today->copy()->subDays(3)->toDateString(),
                'next_calibration_date'    => $today->copy()->addMonths(12)->toDateString(),
                'metadata'                 => [
                    'cal_status' => 'cert_received',
                    'cert_no'    => 'INTERTEK-2025-77345',
                ],
                'image'                    => '/images/calibration-masters/calibration_sheet3_r12_3.jpeg',
                'images'                   => ['calibration_sheet3_r12_3.jpeg', 'calibration_sheet3_r12_4.jpeg'],
            ],

            // ── SPARE (3 entries) ───────────────────────────────────────────
            [
                'sheet_name'               => 'Demo',
                'sheet_order'              => 1,
                'source_row'               => 40,
                'reference_no'             => 'CAL-SP-001',
                'name_type'                => 'Vernier Caliper (Backup)',
                'function'                 => 'Standby unit for VC-2023-001 during calibration',
                'identification_number'    => 'VC-SPARE-B1',
                'measurement_range'        => '0–150 mm',
                'inherent_accuracy'        => '±0.02 mm',
                'usage_accuracy'           => '±0.05 mm',
                'owner_location'           => 'QA Lab – Tool Store',
                'frequency_label'          => 'Yearly',
                'frequency_interval_months'=> 12,
                'last_calibration_date'    => $today->copy()->subMonths(8)->toDateString(),
                'next_calibration_date'    => $today->copy()->addMonths(4)->toDateString(),
                'metadata'                 => ['cal_status' => 'spare'],
                'image'                    => '/images/calibration-masters/calibration_sheet1_r7_3.jpeg',
                'images'                   => ['calibration_sheet1_r7_3.jpeg'],
            ],
            [
                'sheet_name'               => 'Demo',
                'sheet_order'              => 2,
                'source_row'               => 40,
                'reference_no'             => 'CAL-SP-002',
                'name_type'                => 'Digital Thermometer (Backup)',
                'function'                 => 'Standby unit held in QA store',
                'identification_number'    => 'THERM-SPARE-02',
                'measurement_range'        => '-50 to 300 °C',
                'inherent_accuracy'        => '±0.3 °C',
                'usage_accuracy'           => '±1 °C',
                'owner_location'           => 'QA Lab – Tool Store',
                'frequency_label'          => '½ Yearly',
                'frequency_interval_months'=> 6,
                'last_calibration_date'    => $today->copy()->subMonths(4)->toDateString(),
                'next_calibration_date'    => $today->copy()->addMonths(2)->toDateString(),
                'metadata'                 => ['cal_status' => 'spare'],
                'image'                    => '/images/calibration-masters/calibration_sheet2_r17_1.jpeg',
                'images'                   => ['calibration_sheet2_r17_1.jpeg'],
            ],
            [
                'sheet_name'               => 'Demo',
                'sheet_order'              => 3,
                'source_row'               => 40,
                'reference_no'             => 'CAL-SP-003',
                'name_type'                => 'Pressure Gauge (Reserve)',
                'function'                 => 'Reserve unit for critical lines — not in active service',
                'identification_number'    => 'PG-SPARE-R2',
                'measurement_range'        => '0–25 bar',
                'inherent_accuracy'        => '±0.5%',
                'usage_accuracy'           => '±1%',
                'owner_location'           => 'Utility Room – Spare Rack',
                'frequency_label'          => 'Yearly',
                'frequency_interval_months'=> 12,
                'last_calibration_date'    => $today->copy()->subMonths(6)->toDateString(),
                'next_calibration_date'    => $today->copy()->addMonths(6)->toDateString(),
                'metadata'                 => ['cal_status' => 'spare'],
                'image'                    => '/images/calibration-masters/calibration_sheet3_r9_7.jpeg',
                'images'                   => ['calibration_sheet3_r9_7.jpeg'],
            ],

            // ── CALIBRATED / SCHEDULED (5 entries, next_cal > 30 days) ─────
            [
                'sheet_name'               => 'Demo',
                'sheet_order'              => 1,
                'source_row'               => 50,
                'reference_no'             => 'CAL-OK-001',
                'name_type'                => 'Oscilloscope',
                'function'                 => 'Electronic waveform and signal analysis',
                'identification_number'    => 'OSC-ELEC-002',
                'measurement_range'        => 'DC – 200 MHz bandwidth',
                'inherent_accuracy'        => '±1.5%',
                'usage_accuracy'           => '±2%',
                'owner_location'           => 'Engineering Lab',
                'frequency_label'          => 'Yearly',
                'frequency_interval_months'=> 12,
                'last_calibration_date'    => $today->copy()->subDays(30)->toDateString(),
                'next_calibration_date'    => $today->copy()->addDays(335)->toDateString(),
                'metadata'                 => ['performed_by' => 'Intertek KL'],
                'image'                    => '/images/calibration-masters/calibration_sheet1_r10_7.jpeg',
                'images'                   => ['calibration_sheet1_r10_7.jpeg', 'calibration_sheet1_r10_8.jpeg'],
            ],
            [
                'sheet_name'               => 'Demo',
                'sheet_order'              => 2,
                'source_row'               => 50,
                'reference_no'             => 'CAL-OK-002',
                'name_type'                => 'Tachometer (Optical)',
                'function'                 => 'Non-contact rotational speed measurement',
                'identification_number'    => 'TACH-OPT-017',
                'measurement_range'        => '10–99,999 RPM',
                'inherent_accuracy'        => '±0.05%',
                'usage_accuracy'           => '±0.1%',
                'owner_location'           => 'Maintenance Workshop',
                'frequency_label'          => '½ Yearly',
                'frequency_interval_months'=> 6,
                'last_calibration_date'    => $today->copy()->subDays(20)->toDateString(),
                'next_calibration_date'    => $today->copy()->addDays(160)->toDateString(),
                'metadata'                 => ['performed_by' => 'SIRIM QAS International'],
                'image'                    => '/images/calibration-masters/calibration_sheet2_r17_2.jpeg',
                'images'                   => ['calibration_sheet2_r17_2.jpeg'],
            ],
            [
                'sheet_name'               => 'Demo',
                'sheet_order'              => 3,
                'source_row'               => 50,
                'reference_no'             => 'CAL-OK-003',
                'name_type'                => 'Humidity & Temperature Data Logger',
                'function'                 => 'Continuous ambient condition monitoring in warehouse',
                'identification_number'    => 'DL-HT-WHOUSE-001',
                'measurement_range'        => 'RH 0–100% / -10 to 60 °C',
                'inherent_accuracy'        => '±2% RH / ±0.3 °C',
                'usage_accuracy'           => '±3% RH / ±0.5 °C',
                'owner_location'           => 'Warehouse',
                'frequency_label'          => 'Yearly',
                'frequency_interval_months'=> 12,
                'last_calibration_date'    => $today->copy()->subDays(45)->toDateString(),
                'next_calibration_date'    => $today->copy()->addDays(320)->toDateString(),
                'metadata'                 => ['performed_by' => 'Bureau Veritas'],
                'image'                    => '/images/calibration-masters/calibration_sheet3_r12_4.jpeg',
                'images'                   => ['calibration_sheet3_r12_4.jpeg'],
            ],
            [
                'sheet_name'               => 'Demo',
                'sheet_order'              => 4,
                'source_row'               => 50,
                'reference_no'             => 'CAL-OK-004',
                'name_type'                => 'Caliper (Digital)',
                'function'                 => 'Digital readout caliper for in-process measurement',
                'identification_number'    => 'CAL-DIG-IPM-009',
                'measurement_range'        => '0–200 mm',
                'inherent_accuracy'        => '±0.01 mm',
                'usage_accuracy'           => '±0.02 mm',
                'owner_location'           => 'Production – Line 1',
                'frequency_label'          => 'Yearly',
                'frequency_interval_months'=> 12,
                'last_calibration_date'    => $today->copy()->subDays(60)->toDateString(),
                'next_calibration_date'    => $today->copy()->addDays(305)->toDateString(),
                'metadata'                 => ['performed_by' => 'In-house calibration lab'],
                'image'                    => '/images/calibration-masters/calibration_sheet-4_r10_8.jpeg',
                'images'                   => ['calibration_sheet-4_r10_8.jpeg', 'calibration_sheet-4_r10_9.jpeg'],
            ],
            [
                'sheet_name'               => 'Demo',
                'sheet_order'              => 4,
                'source_row'               => 51,
                'reference_no'             => 'CAL-OK-005',
                'name_type'                => 'Angle Plate (Precision)',
                'function'                 => 'Reference standard for angular setup on surface plate',
                'identification_number'    => 'AP-PREC-REF-001',
                'measurement_range'        => '90° ± tolerance class B',
                'inherent_accuracy'        => '±5 arc-second',
                'usage_accuracy'           => '±10 arc-second',
                'owner_location'           => 'Metrology Room',
                'frequency_label'          => '2 Yearly',
                'frequency_interval_months'=> 24,
                'last_calibration_date'    => $today->copy()->subMonths(2)->toDateString(),
                'next_calibration_date'    => $today->copy()->addMonths(22)->toDateString(),
                'metadata'                 => ['performed_by' => 'SIRIM QAS International'],
                'image'                    => '/images/calibration-masters/calibration_sheet-4_r7_3.jpeg',
                'images'                   => ['calibration_sheet-4_r7_3.jpeg'],
            ],
        ];
    }
}
