<?php

namespace Database\Seeders;

use App\Models\Customer;
use Illuminate\Database\Seeder;

class CustomerSeeder extends Seeder
{
    /**
     * Seed realistic customer records.
     */
    public function run(): void
    {
        $customers = [
            [
                'customer_code' => 'CUST-0001',
                'customer_name' => 'Acme Manufacturing Corp',
                'status' => 'Active',
                'country' => 'Philippines',
                'state' => 'NCR',
                'city' => 'Makati City',
                'address' => '24 Jupiter St., Bel-Air',
                'postal_code' => '1209',
                'contact_person' => 'Elaine Robles',
                'contact_number' => '+63 2 8899 1234',
                'email' => 'elaine.robles@acmeph.com',
                'business_name' => 'Acme Manufacturing Corp',
                'business_registration_no' => 'SEC-2015-0001',
                'tax_id' => 'TIN-567-123-890',
                'industry' => 'Consumer Goods',
                'payment_terms' => 'NET 30',
                'tax_type' => 'VAT',
                'billing_address' => '24 Jupiter St., Makati',
                'shipping_address' => 'Warehouse 12, Cabuyao Laguna',
                'customer_group' => 'Key Accounts',
                'sales_representative' => 'Miguel Ramos',
                'pricing_tier' => 'Tier 1',
                'remarks' => 'Prefers quarterly reviews.',
            ],
            [
                'customer_code' => 'CUST-0002',
                'customer_name' => 'Greenfields Agricultural Supply',
                'status' => 'Active',
                'country' => 'Philippines',
                'state' => 'Pampanga',
                'city' => 'San Fernando',
                'address' => 'MacArthur Highway',
                'postal_code' => '2000',
                'contact_person' => 'Rico Dizon',
                'contact_number' => '+63 45 888 4567',
                'email' => 'rico.dizon@greenfields.com',
                'business_name' => 'Greenfields Agricultural Supply',
                'tax_id' => 'TIN-451-987-222',
                'industry' => 'Agriculture',
                'payment_terms' => 'NET 45',
                'tax_type' => 'VAT',
                'billing_address' => 'MacArthur Highway, San Fernando',
                'shipping_address' => 'Brgy. Sindalan, San Fernando',
                'customer_group' => 'Regional',
                'sales_representative' => 'Anna Lim',
                'pricing_tier' => 'Tier 2',
                'remarks' => 'Seasonal spikes during harvest.',
            ],
            [
                'customer_code' => 'CUST-0003',
                'customer_name' => 'Northstar Retailers Inc.',
                'status' => 'Active',
                'country' => 'Philippines',
                'state' => 'Cebu',
                'city' => 'Cebu City',
                'address' => '888 Gen. Maxilom Ave',
                'postal_code' => '6000',
                'contact_person' => 'Sharon Uy',
                'contact_number' => '+63 32 231 7788',
                'email' => 'sharon.uy@northstar.com',
                'industry' => 'Retail',
                'payment_terms' => 'COD',
                'tax_type' => 'VAT',
                'billing_address' => '888 Gen. Maxilom Ave, Cebu',
                'shipping_address' => 'Northstar Warehouse, Mandaue',
                'customer_group' => 'SME',
                'sales_representative' => 'Leah Go',
                'pricing_tier' => 'Tier 3',
                'remarks' => 'Requires Friday deliveries.',
            ],
            [
                'customer_code' => 'CUST-0004',
                'customer_name' => 'Blue Harbor Trading',
                'status' => 'Active',
                'country' => 'Philippines',
                'state' => 'Davao del Sur',
                'city' => 'Davao City',
                'address' => 'Lanang Business Park',
                'postal_code' => '8000',
                'contact_person' => 'Joey Salazar',
                'contact_number' => '+63 82 225 4433',
                'email' => 'joey.salazar@blueharbor.com',
                'industry' => 'Distribution',
                'payment_terms' => 'NET 30',
                'tax_type' => 'VAT',
                'billing_address' => 'Lanang Business Park, Davao',
                'shipping_address' => 'Panacan Wharf, Davao',
                'customer_group' => 'Regional',
                'sales_representative' => 'Ramon Dizon',
                'pricing_tier' => 'Tier 2',
                'remarks' => 'Handles Mindanao accounts.',
            ],
            [
                'customer_code' => 'CUST-0005',
                'customer_name' => 'Casa Delights Bakery',
                'status' => 'Active',
                'country' => 'Philippines',
                'state' => 'NCR',
                'city' => 'Quezon City',
                'address' => 'Tomas Morato Ave',
                'postal_code' => '1112',
                'contact_person' => 'Bianca Ortega',
                'contact_number' => '+63 2 8371 9988',
                'email' => 'bianca.ortega@casadelights.com',
                'industry' => 'Food & Beverage',
                'payment_terms' => 'NET 15',
                'tax_type' => 'VAT',
                'billing_address' => 'Tomas Morato Ave, QC',
                'shipping_address' => 'Warehouse 8, Novaliches',
                'customer_group' => 'SME',
                'sales_representative' => 'Paula Villanueva',
                'pricing_tier' => 'Tier 4',
                'remarks' => 'Weekly replenishment schedule.',
            ],
            [
                'customer_code' => 'CUST-0006',
                'customer_name' => 'Sunrise General Merchandising',
                'status' => 'Active',
                'country' => 'Philippines',
                'state' => 'Laguna',
                'city' => 'Santa Rosa',
                'address' => 'Greenfield City',
                'postal_code' => '4026',
                'contact_person' => 'Harold Chua',
                'contact_number' => '+63 49 523 4411',
                'email' => 'harold.chua@sunrisegm.com',
                'industry' => 'Wholesale',
                'payment_terms' => 'NET 30',
                'tax_type' => 'VAT',
                'billing_address' => 'Greenfield City, Sta. Rosa',
                'shipping_address' => 'Technopark Drive, Sta. Rosa',
                'customer_group' => 'Regional',
                'sales_representative' => 'Nate Aquino',
                'pricing_tier' => 'Tier 3',
                'remarks' => 'Requires palletized shipments.',
            ],
            [
                'customer_code' => 'CUST-0007',
                'customer_name' => 'Luxe Living Furnishings',
                'status' => 'Active',
                'country' => 'Philippines',
                'state' => 'NCR',
                'city' => 'Taguig City',
                'address' => 'Bonifacio Global City',
                'postal_code' => '1630',
                'contact_person' => 'Jamie Pacheco',
                'contact_number' => '+63 2 8806 7722',
                'email' => 'jamie.pacheco@luxeliving.com',
                'industry' => 'Home & Living',
                'payment_terms' => 'NET 45',
                'tax_type' => 'VAT',
                'billing_address' => '5th Ave., BGC',
                'shipping_address' => 'Gate 3, FTI, Taguig',
                'customer_group' => 'Key Accounts',
                'sales_representative' => 'Kaye Ramos',
                'pricing_tier' => 'Tier 1',
                'remarks' => 'High-value interior projects.',
            ],
            [
                'customer_code' => 'CUST-0008',
                'customer_name' => 'Island Fresh Seafood',
                'status' => 'Active',
                'country' => 'Philippines',
                'state' => 'Palawan',
                'city' => 'Puerto Princesa',
                'address' => 'Rizal Ave. Ext.',
                'postal_code' => '5300',
                'contact_person' => 'Marco Soriano',
                'contact_number' => '+63 48 723 5566',
                'email' => 'marco.soriano@islandfresh.com',
                'industry' => 'Food & Beverage',
                'payment_terms' => 'COD',
                'tax_type' => 'Non-VAT',
                'billing_address' => 'Rizal Ave., Puerto Princesa',
                'shipping_address' => 'Fishport Rd., Puerto Princesa',
                'customer_group' => 'SME',
                'sales_representative' => 'Jonas Delos Reyes',
                'pricing_tier' => 'Tier 4',
                'remarks' => 'Ships via cold chain.',
            ],
            [
                'customer_code' => 'CUST-0009',
                'customer_name' => 'Metro Industrial Hardware',
                'status' => 'Active',
                'country' => 'Philippines',
                'state' => 'Bulacan',
                'city' => 'Meycauayan',
                'address' => 'Malhacan Road',
                'postal_code' => '3020',
                'contact_person' => 'Geraldine Tolentino',
                'contact_number' => '+63 44 934 8899',
                'email' => 'geraldine.tolentino@metrohardware.com',
                'industry' => 'Industrial Supply',
                'payment_terms' => 'NET 60',
                'tax_type' => 'VAT',
                'billing_address' => 'Malhacan Road, Meycauayan',
                'shipping_address' => 'Phase 2, Sterling Industrial Park',
                'customer_group' => 'Key Accounts',
                'sales_representative' => 'Leo Pascual',
                'pricing_tier' => 'Tier 1',
                'remarks' => 'Long-term maintenance contracts.',
            ],
            [
                'customer_code' => 'CUST-0010',
                'customer_name' => 'Bright Minds Learning Hub',
                'status' => 'Active',
                'country' => 'Philippines',
                'state' => 'NCR',
                'city' => 'Pasig City',
                'address' => 'Ortigas Center',
                'postal_code' => '1605',
                'contact_person' => 'Liza Manalo',
                'contact_number' => '+63 2 8634 6023',
                'email' => 'liza.manalo@brightminds.edu.ph',
                'industry' => 'Education',
                'payment_terms' => 'NET 30',
                'tax_type' => 'VAT',
                'billing_address' => 'Ortigas Center, Pasig',
                'shipping_address' => 'C. Raymundo Ave., Pasig',
                'customer_group' => 'SME',
                'sales_representative' => 'Ina Bautista',
                'pricing_tier' => 'Tier 3',
                'remarks' => 'Orders start of every semester.',
            ],
            [
                'customer_code' => 'CUST-0011',
                'customer_name' => 'Trident Marine Logistics',
                'status' => 'Active',
                'country' => 'Philippines',
                'state' => 'Zamboanga del Sur',
                'city' => 'Zamboanga City',
                'address' => 'Gov. Camins Ave',
                'postal_code' => '7000',
                'contact_person' => 'Dennis Velasco',
                'contact_number' => '+63 62 955 0544',
                'email' => 'dennis.velasco@tridentmarine.ph',
                'industry' => 'Logistics',
                'payment_terms' => 'NET 45',
                'tax_type' => 'VAT',
                'billing_address' => 'Gov. Camins Ave, Zamboanga',
                'shipping_address' => 'Port Area, Zamboanga',
                'customer_group' => 'Regional',
                'sales_representative' => 'Owen Mercado',
                'pricing_tier' => 'Tier 2',
                'remarks' => 'Requires bill of lading copies.',
            ],
            [
                'customer_code' => 'CUST-0012',
                'customer_name' => 'Wellness Junction Pharmacies',
                'status' => 'Active',
                'country' => 'Philippines',
                'state' => 'NCR',
                'city' => 'Manila',
                'address' => 'Ermita District',
                'postal_code' => '1000',
                'contact_person' => 'Carla Mendoza',
                'contact_number' => '+63 2 8527 3344',
                'email' => 'carla.mendoza@wellnessjunction.ph',
                'industry' => 'Healthcare',
                'payment_terms' => 'NET 30',
                'tax_type' => 'VAT',
                'billing_address' => 'Ermita, Manila',
                'shipping_address' => 'Sta. Ana Warehouse, Manila',
                'customer_group' => 'Key Accounts',
                'sales_representative' => 'Sophie Reyes',
                'pricing_tier' => 'Tier 1',
                'remarks' => 'Needs FDA certificates on file.',
            ],
            [
                'customer_code' => 'CUST-0013',
                'customer_name' => 'Golden Harvest Rice Dealers',
                'status' => 'Active',
                'country' => 'Philippines',
                'state' => 'Nueva Ecija',
                'city' => 'Cabanatuan City',
                'address' => 'Maharlika Highway',
                'postal_code' => '3100',
                'contact_person' => 'Noel Panganiban',
                'contact_number' => '+63 44 463 3388',
                'email' => 'noel.panganiban@goldenharvest.ph',
                'industry' => 'Agriculture',
                'payment_terms' => 'NET 15',
                'tax_type' => 'VAT',
                'billing_address' => 'Maharlika Highway, Cabanatuan',
                'shipping_address' => 'Talavera Dry Warehouse',
                'customer_group' => 'Regional',
                'sales_representative' => 'Benjie Cruz',
                'pricing_tier' => 'Tier 3',
                'remarks' => 'Prefers sack labeling.',
            ],
            [
                'customer_code' => 'CUST-0014',
                'customer_name' => 'VistaTech Electronics',
                'status' => 'Active',
                'country' => 'Philippines',
                'state' => 'NCR',
                'city' => 'Paranaque City',
                'address' => 'ASEANA City',
                'postal_code' => '1701',
                'contact_person' => 'Rey Malabanan',
                'contact_number' => '+63 2 8826 5600',
                'email' => 'rey.malabanan@vistatech.ph',
                'industry' => 'Electronics',
                'payment_terms' => 'NET 60',
                'tax_type' => 'VAT',
                'billing_address' => 'ASEANA City, Paranaque',
                'shipping_address' => 'Gateway Logistics, Paranaque',
                'customer_group' => 'Key Accounts',
                'sales_representative' => 'Allan Pua',
                'pricing_tier' => 'Tier 1',
                'remarks' => 'Needs ESD-safe packaging.',
            ],
            [
                'customer_code' => 'CUST-0015',
                'customer_name' => 'Southern Peaks Resort',
                'status' => 'Active',
                'country' => 'Philippines',
                'state' => 'Benguet',
                'city' => 'Baguio City',
                'address' => 'Camp John Hay',
                'postal_code' => '2600',
                'contact_person' => 'Mia Vergara',
                'contact_number' => '+63 74 442 9911',
                'email' => 'mia.vergara@southernpeaks.ph',
                'industry' => 'Hospitality',
                'payment_terms' => 'NET 30',
                'tax_type' => 'VAT',
                'billing_address' => 'Camp John Hay, Baguio',
                'shipping_address' => 'Loakan Rd., Baguio',
                'customer_group' => 'SME',
                'sales_representative' => 'Veronica Lao',
                'pricing_tier' => 'Tier 3',
                'remarks' => 'Delivers every 2nd Tuesday.',
            ],
            [
                'customer_code' => 'CUST-0016',
                'customer_name' => 'Urban Bites Convenience',
                'status' => 'Active',
                'country' => 'Philippines',
                'state' => 'NCR',
                'city' => 'Manila',
                'address' => 'Paco District',
                'postal_code' => '1007',
                'contact_person' => 'Arvin Bautista',
                'contact_number' => '+63 2 8567 8890',
                'email' => 'arvin.bautista@urbanbites.ph',
                'industry' => 'Retail',
                'payment_terms' => 'NET 15',
                'tax_type' => 'VAT',
                'billing_address' => 'Paco, Manila',
                'shipping_address' => 'Pandacan Warehouse, Manila',
                'customer_group' => 'SME',
                'sales_representative' => 'Clarisse Uy',
                'pricing_tier' => 'Tier 4',
                'remarks' => 'Operates 12 stores.',
            ],
            [
                'customer_code' => 'CUST-0017',
                'customer_name' => 'Mindoro Agro Traders',
                'status' => 'Active',
                'country' => 'Philippines',
                'state' => 'Oriental Mindoro',
                'city' => 'Calapan',
                'address' => 'Gov. Infantado St.',
                'postal_code' => '5200',
                'contact_person' => 'Felix Adriano',
                'contact_number' => '+63 43 288 5500',
                'email' => 'felix.adriano@mindoroagro.com',
                'industry' => 'Agriculture',
                'payment_terms' => 'NET 30',
                'tax_type' => 'VAT',
                'billing_address' => 'Gov. Infantado St., Calapan',
                'shipping_address' => 'Port of Calapan, Calero Rd.',
                'customer_group' => 'Regional',
                'sales_representative' => 'Harvey Lim',
                'pricing_tier' => 'Tier 3',
                'remarks' => 'Ships via RORO.',
            ],
            [
                'customer_code' => 'CUST-0018',
                'customer_name' => 'Eco Savers Cooperative',
                'status' => 'Active',
                'country' => 'Philippines',
                'state' => 'Iloilo',
                'city' => 'Iloilo City',
                'address' => 'Diversion Road',
                'postal_code' => '5000',
                'contact_person' => 'Grace Javelosa',
                'contact_number' => '+63 33 337 4422',
                'email' => 'grace.javelosa@ecosavers.coop',
                'industry' => 'Cooperative',
                'payment_terms' => 'NET 30',
                'tax_type' => 'Non-VAT',
                'billing_address' => 'Diversion Road, Iloilo',
                'shipping_address' => 'Lapaz Warehouse, Iloilo',
                'customer_group' => 'SME',
                'sales_representative' => 'Marco Uy',
                'pricing_tier' => 'Tier 4',
                'remarks' => 'Community-based buyers.',
            ],
            [
                'customer_code' => 'CUST-0019',
                'customer_name' => 'Heritage Wines & Spirits',
                'status' => 'Active',
                'country' => 'Philippines',
                'state' => 'Batangas',
                'city' => 'Lipa City',
                'address' => 'JP Laurel Highway',
                'postal_code' => '4217',
                'contact_person' => 'Rina Beltran',
                'contact_number' => '+63 43 756 8800',
                'email' => 'rina.beltran@heritagewines.ph',
                'industry' => 'Food & Beverage',
                'payment_terms' => 'NET 30',
                'tax_type' => 'VAT',
                'billing_address' => 'JP Laurel Highway, Lipa',
                'shipping_address' => 'Tambo Exit Warehouse',
                'customer_group' => 'Regional',
                'sales_representative' => 'Patrick Olivarez',
                'pricing_tier' => 'Tier 2',
                'remarks' => 'Requires bonded trucking.',
            ],
            [
                'customer_code' => 'CUST-0020',
                'customer_name' => 'Digital Hive Solutions',
                'status' => 'Active',
                'country' => 'Philippines',
                'state' => 'NCR',
                'city' => 'Pasay City',
                'address' => 'CBP-1, MOA Complex',
                'postal_code' => '1300',
                'contact_person' => 'Iris Bautista',
                'contact_number' => '+63 2 8854 1266',
                'email' => 'iris.bautista@digitalhive.ph',
                'industry' => 'Technology',
                'payment_terms' => 'NET 60',
                'tax_type' => 'VAT',
                'billing_address' => 'CBP-1, MOA Complex, Pasay',
                'shipping_address' => 'Warehouse 3, PITX Logistics Hub',
                'customer_group' => 'Key Accounts',
                'sales_representative' => 'Nikki Soriano',
                'pricing_tier' => 'Tier 1',
                'remarks' => 'Needs quarterly SLA review.',
            ],
        ];

        foreach ($customers as $customer) {
            Customer::updateOrCreate(
                ['customer_code' => $customer['customer_code']],
                $customer
            );
        }
    }
}
