<?php

namespace Database\Seeders;

use App\Models\Customer;
use App\Models\TemplateRoute;
use App\Models\WorkOrder;
use Illuminate\Database\Seeder;

class WorkOrderSeeder extends Seeder
{
    public function run(): void
    {
        $customerIds = Customer::pluck('id')->all();
        $templateRoutes = TemplateRoute::all();

        if (count($customerIds) === 0 || $templateRoutes->isEmpty()) {
            $this->command?->warn('No customers or template routes found. Skipping work order seeding.');

            return;
        }

        $orders = [
            [
                'work_order_no' => 'WO-2025-001',
                'priority_type' => 'High(2 - 3)',
                'date' => '2025-01-05',
                'posted_date' => '2025-01-06',
                'document_date' => '2025-01-05',
                'due_date' => '2025-01-20',
                'date_printed' => '2025-01-06',
                'document_type' => 'Production',
                'printed_by' => 'Ana D.',
                'qr_code' => 'QR-001',
                'size' => '500x300 mm',
                'websize' => '450 mm',
                'material' => 'Kraft Paper',
                'colours' => 'CMYK',
                'butt' => 'Standard',
                'interval' => '1.2 sec',
                'radius' => 'R5',
                'material_not_number' => 'MP-2201',
                'operator_code' => 'OP-100',
                'number_of_used_up' => 2000,
                'number_of_process' => 3,
                'meta_remarks' => 'Rush order for new product launch.',
            ],
            [
                'work_order_no' => 'WO-2025-002',
                'priority_type' => 'normal',
                'date' => '2025-01-08',
                'posted_date' => '2025-01-09',
                'document_date' => '2025-01-08',
                'due_date' => '2025-01-25',
                'date_printed' => '2025-01-09',
                'document_type' => 'Maintenance',
                'printed_by' => 'Ben R.',
                'qr_code' => 'QR-002',
                'size' => '600x350 mm',
                'websize' => '520 mm',
                'material' => 'Plastic Film',
                'colours' => 'Spot Red',
                'butt' => 'Tight',
                'interval' => '0.9 sec',
                'radius' => 'R3',
                'material_not_number' => 'PF-885',
                'operator_code' => 'OP-112',
                'number_of_used_up' => 1500,
                'number_of_process' => 4,
                'meta_remarks' => 'Include new ink mix.',
            ],
            [
                'work_order_no' => 'WO-2025-003',
                'priority_type' => 'High(4 - 8)',
                'date' => '2025-01-10',
                'posted_date' => '2025-01-10',
                'document_date' => '2025-01-10',
                'due_date' => '2025-02-02',
                'date_printed' => '2025-01-10',
                'document_type' => 'Production',
                'printed_by' => 'Carl S.',
                'qr_code' => 'QR-003',
                'size' => 'A3',
                'websize' => '470 mm',
                'material' => 'Art Paper',
                'colours' => 'Pantone 186C',
                'butt' => 'Standard',
                'interval' => '1.5 sec',
                'radius' => 'R4',
                'material_not_number' => 'AP-556',
                'operator_code' => 'OP-118',
                'number_of_used_up' => 3000,
                'number_of_process' => 5,
                'meta_remarks' => 'Customer requested extra QC.',
            ],
            [
                'work_order_no' => 'WO-2025-004',
                'priority_type' => 'low',
                'date' => '2025-01-12',
                'posted_date' => '2025-01-13',
                'document_date' => '2025-01-12',
                'due_date' => '2025-01-28',
                'date_printed' => '2025-01-13',
                'document_type' => 'Prototype',
                'printed_by' => 'Dana U.',
                'qr_code' => 'QR-004',
                'size' => '400x250 mm',
                'websize' => '420 mm',
                'material' => 'Synthetic Paper',
                'colours' => 'CMY',
                'butt' => 'Loose',
                'interval' => '1.0 sec',
                'radius' => 'R2',
                'material_not_number' => 'SP-133',
                'operator_code' => 'OP-102',
                'number_of_used_up' => 1200,
                'number_of_process' => 2,
                'meta_remarks' => 'Prototype for eco-pack.',
            ],
            [
                'work_order_no' => 'WO-2025-005',
                'priority_type' => 'normal',
                'date' => '2025-01-14',
                'posted_date' => '2025-01-15',
                'document_date' => '2025-01-14',
                'due_date' => '2025-02-05',
                'date_printed' => null,
                'document_type' => 'Production',
                'printed_by' => null,
                'qr_code' => 'QR-005',
                'size' => '700x400 mm',
                'websize' => '600 mm',
                'material' => 'Corrugated Board',
                'colours' => 'Pantone 431C',
                'butt' => 'Standard',
                'interval' => '1.8 sec',
                'radius' => 'R6',
                'material_not_number' => 'CB-667',
                'operator_code' => 'OP-130',
                'number_of_used_up' => 5000,
                'number_of_process' => 6,
                'meta_remarks' => 'Bulk run, schedule night shift.',
            ],
            [
                'work_order_no' => 'WO-2025-006',
                'priority_type' => 'High(9 - 12)',
                'date' => '2025-01-18',
                'posted_date' => '2025-01-18',
                'document_date' => '2025-01-18',
                'due_date' => '2025-02-07',
                'date_printed' => '2025-01-18',
                'document_type' => 'Maintenance',
                'printed_by' => 'Earl M.',
                'qr_code' => 'QR-006',
                'size' => '500x500 mm',
                'websize' => '480 mm',
                'material' => 'PVC Film',
                'colours' => 'White',
                'butt' => 'Tight',
                'interval' => '0.8 sec',
                'radius' => 'R2',
                'material_not_number' => 'PVC-120',
                'operator_code' => 'OP-125',
                'number_of_used_up' => 800,
                'number_of_process' => 3,
                'meta_remarks' => 'Machine alignment required.',
            ],
            [
                'work_order_no' => 'WO-2025-007',
                'priority_type' => 'Urgent(2 - 3)',
                'date' => '2025-01-20',
                'posted_date' => '2025-01-21',
                'document_date' => '2025-01-20',
                'due_date' => '2025-02-10',
                'date_printed' => '2025-01-21',
                'document_type' => 'Production',
                'printed_by' => 'Faye Q.',
                'qr_code' => 'QR-007',
                'size' => '300x200 mm',
                'websize' => '320 mm',
                'material' => 'Foil',
                'colours' => 'Gold + Black',
                'butt' => 'Standard',
                'interval' => '1.1 sec',
                'radius' => 'R1',
                'material_not_number' => 'FO-441',
                'operator_code' => 'OP-140',
                'number_of_used_up' => 2200,
                'number_of_process' => 4,
                'meta_remarks' => 'Luxury sachet run.',
            ],
            [
                'work_order_no' => 'WO-2025-008',
                'priority_type' => 'Urgent(4 - 8)',
                'date' => '2025-01-22',
                'posted_date' => '2025-01-22',
                'document_date' => '2025-01-22',
                'due_date' => '2025-02-12',
                'date_printed' => '2025-01-22',
                'document_type' => 'Production',
                'printed_by' => 'Gina T.',
                'qr_code' => 'QR-008',
                'size' => 'A4',
                'websize' => '297 mm',
                'material' => 'Bond Paper',
                'colours' => 'Black',
                'butt' => 'Loose',
                'interval' => '1.3 sec',
                'radius' => 'R2',
                'material_not_number' => 'BP-330',
                'operator_code' => 'OP-152',
                'number_of_used_up' => 900,
                'number_of_process' => 2,
                'meta_remarks' => 'Invoice booklet run.',
            ],
            [
                'work_order_no' => 'WO-2025-009',
                'priority_type' => 'Urgent(9 - 12)',
                'date' => '2025-01-24',
                'posted_date' => '2025-01-25',
                'document_date' => '2025-01-24',
                'due_date' => '2025-02-15',
                'date_printed' => '2025-01-25',
                'document_type' => 'Prototype',
                'printed_by' => 'Hiro I.',
                'qr_code' => 'QR-009',
                'size' => '350x250 mm',
                'websize' => '360 mm',
                'material' => 'Bio-plastic Film',
                'colours' => 'Green',
                'butt' => 'Standard',
                'interval' => '1.0 sec',
                'radius' => 'R3',
                'material_not_number' => 'BF-205',
                'operator_code' => 'OP-166',
                'number_of_used_up' => 600,
                'number_of_process' => 3,
                'meta_remarks' => 'Sustainability test batch.',
            ],
            [
                'work_order_no' => 'WO-2025-010',
                'priority_type' => 'High(2 - 3)',
                'date' => '2025-01-28',
                'posted_date' => '2025-01-29',
                'document_date' => '2025-01-28',
                'due_date' => '2025-02-20',
                'date_printed' => '2025-01-29',
                'document_type' => 'Production',
                'printed_by' => 'Ivan L.',
                'qr_code' => 'QR-010',
                'size' => '450x300 mm',
                'websize' => '430 mm',
                'material' => 'Recycled Board',
                'colours' => 'CMYK + White',
                'butt' => 'Tight',
                'interval' => '1.4 sec',
                'radius' => 'R4',
                'material_not_number' => 'RB-990',
                'operator_code' => 'OP-172',
                'number_of_used_up' => 2800,
                'number_of_process' => 4,
                'meta_remarks' => 'Seasonal cartons.',
            ],
        ];

        foreach ($orders as $index => $order) {
            $templateRoute = $templateRoutes[$index % $templateRoutes->count()];
            $order['customer_id'] = $customerIds[$index % count($customerIds)];
            $order['template_route_id'] = $templateRoute->id;
            // persist template metadata snapshot on the work order
            $order['metadata'] = $templateRoute->metadata;
            WorkOrder::create($order);
        }
    }
}
