<?php

namespace Database\Seeders;

use App\Models\Customer;
use App\Models\TemplateRoute;
use App\Models\WorkOrder;
use Illuminate\Database\Seeder;

class WorkOrderSeeder extends Seeder
{
    public function run(): void
    {
        $customers = Customer::select('id', 'customer_code', 'customer_name')->get()->keyBy('id');
        $customerIds = $customers->pluck('id')->all();
        $templateRoutes = TemplateRoute::all();

        if (count($customerIds) === 0 || $templateRoutes->isEmpty()) {
            $this->command?->warn('No customers or template routes found. Skipping work order seeding.');

            return;
        }

        $orders = [
            [
                'work_order_no' => 'WO-2025-001',
                'batch_number' => '050125T0800',
                'selected' => true,
                'mes_batch_no' => 'BATCH-0001',
                'material_1_code' => 'MAT-001',
                'material_2_code' => 'INK-CMYK',
                'material_3_code' => 'SUB-100',
                'material_4_code' => null,
                'customer_part_number' => 'CP-1001',
                'production_due_date' => '2025-01-20',
                'quantity_to_produce' => 5000,
                'quantity_produced' => 1200,
                'forecast_quantity' => 5200,
                'die_cut' => 'DC-100',
                'internal_remark' => 'Rush order for new product launch.',
                'requested_delivery_date' => '2025-01-22',
                'no_of_colours' => 4,
                'sales_person_code' => 'SP-001',
                'order_date' => '2025-01-05',
                'production_date_completed' => null,
                'production_qty_completed' => 0,
                'qr_code' => 'QR-001',
            ],
            [
                'work_order_no' => 'WO-2025-002',
                'batch_number' => '080125T0915',
                'selected' => false,
                'mes_batch_no' => 'BATCH-0002',
                'material_1_code' => 'MAT-010',
                'material_2_code' => 'INK-BLK',
                'material_3_code' => null,
                'material_4_code' => null,
                'customer_part_number' => 'CP-1002',
                'production_due_date' => '2025-01-25',
                'quantity_to_produce' => 3000,
                'quantity_produced' => 3000,
                'forecast_quantity' => 3200,
                'die_cut' => 'DC-120',
                'internal_remark' => 'Include new ink mix.',
                'requested_delivery_date' => '2025-01-26',
                'no_of_colours' => 1,
                'sales_person_code' => 'SP-002',
                'order_date' => '2025-01-08',
                'production_date_completed' => '2025-01-24',
                'production_qty_completed' => 3000,
                'qr_code' => 'QR-002',
            ],
            [
                'work_order_no' => 'WO-2025-003',
                'batch_number' => '100125T1345',
                'selected' => true,
                'mes_batch_no' => 'BATCH-0003',
                'material_1_code' => 'MAT-025',
                'material_2_code' => 'INK-RED',
                    'material_3_code' => 'FOIL-01',
                'material_4_code' => null,
                'customer_part_number' => 'CP-1003',
                'production_due_date' => '2025-02-02',
                'quantity_to_produce' => 8000,
                'quantity_produced' => 3500,
                'forecast_quantity' => 8200,
                'die_cut' => 'DC-200',
                'internal_remark' => 'Customer requested extra QC.',
                'requested_delivery_date' => '2025-02-04',
                'no_of_colours' => 2,
                'sales_person_code' => 'SP-003',
                'order_date' => '2025-01-10',
                'production_date_completed' => null,
                'production_qty_completed' => 0,
                'qr_code' => 'QR-003',
            ],
            [
                'work_order_no' => 'WO-2025-004',
                'batch_number' => '120125T1010',
                'selected' => false,
                'mes_batch_no' => 'BATCH-0004',
                'material_1_code' => 'MAT-030',
                'material_2_code' => null,
                'material_3_code' => null,
                'material_4_code' => null,
                'customer_part_number' => 'CP-1004',
                'production_due_date' => '2025-01-28',
                'quantity_to_produce' => 1200,
                'quantity_produced' => 1200,
                'forecast_quantity' => 1500,
                'die_cut' => 'DC-050',
                'internal_remark' => 'Prototype for eco-pack.',
                'requested_delivery_date' => '2025-01-29',
                'no_of_colours' => 3,
                'sales_person_code' => 'SP-004',
                'order_date' => '2025-01-12',
                'production_date_completed' => '2025-01-26',
                'production_qty_completed' => 1200,
                'qr_code' => 'QR-004',
            ],
            [
                'work_order_no' => 'WO-2025-005',
                'batch_number' => '140125T0830',
                'selected' => true,
                'mes_batch_no' => 'BATCH-0005',
                'material_1_code' => 'MAT-045',
                'material_2_code' => 'INK-P431',
                'material_3_code' => 'SUB-225',
                'material_4_code' => null,
                'customer_part_number' => 'CP-1005',
                'production_due_date' => '2025-02-05',
                'quantity_to_produce' => 6000,
                'quantity_produced' => 0,
                'forecast_quantity' => 6200,
                'die_cut' => 'DC-320',
                'internal_remark' => 'Bulk run, schedule night shift.',
                'requested_delivery_date' => '2025-02-06',
                'no_of_colours' => 1,
                'sales_person_code' => 'SP-005',
                'order_date' => '2025-01-14',
                'production_date_completed' => null,
                'production_qty_completed' => 0,
                'qr_code' => 'QR-005',
            ],
            [
                'work_order_no' => 'WO-2025-006',
                'batch_number' => '180125T1540',
                'selected' => false,
                'mes_batch_no' => 'BATCH-0006',
                'material_1_code' => 'MAT-050',
                'material_2_code' => 'INK-WHT',
                'material_3_code' => null,
                'material_4_code' => null,
                'customer_part_number' => 'CP-1006',
                'production_due_date' => '2025-02-07',
                'quantity_to_produce' => 800,
                'quantity_produced' => 800,
                'forecast_quantity' => 850,
                'die_cut' => 'DC-010',
                'internal_remark' => 'Machine alignment required.',
                'requested_delivery_date' => '2025-02-08',
                'no_of_colours' => 1,
                'sales_person_code' => 'SP-006',
                'order_date' => '2025-01-18',
                'production_date_completed' => '2025-01-30',
                'production_qty_completed' => 800,
                'qr_code' => 'QR-006',
            ],
            [
                'work_order_no' => 'WO-2025-007',
                'batch_number' => '200125T0935',
                'selected' => true,
                'mes_batch_no' => 'BATCH-0007',
                'material_1_code' => 'MAT-070',
                'material_2_code' => 'INK-GLD',
                'material_3_code' => 'INK-BLK',
                'material_4_code' => null,
                'customer_part_number' => 'CP-1007',
                'production_due_date' => '2025-02-10',
                'quantity_to_produce' => 2200,
                'quantity_produced' => 400,
                'forecast_quantity' => 2500,
                'die_cut' => 'DC-440',
                'internal_remark' => 'Luxury sachet run.',
                'requested_delivery_date' => '2025-02-11',
                'no_of_colours' => 2,
                'sales_person_code' => 'SP-007',
                'order_date' => '2025-01-20',
                'production_date_completed' => null,
                'production_qty_completed' => 0,
                'qr_code' => 'QR-007',
            ],
            [
                'work_order_no' => 'WO-2025-008',
                'batch_number' => '220125T1100',
                'selected' => false,
                'mes_batch_no' => 'BATCH-0008',
                'material_1_code' => 'MAT-080',
                'material_2_code' => 'INK-BLK',
                'material_3_code' => null,
                'material_4_code' => null,
                'customer_part_number' => 'CP-1008',
                'production_due_date' => '2025-02-12',
                'quantity_to_produce' => 900,
                'quantity_produced' => 600,
                'forecast_quantity' => 950,
                'die_cut' => 'DC-012',
                'internal_remark' => 'Invoice booklet run.',
                'requested_delivery_date' => '2025-02-13',
                'no_of_colours' => 1,
                'sales_person_code' => 'SP-008',
                'order_date' => '2025-01-22',
                'production_date_completed' => null,
                'production_qty_completed' => 0,
                'qr_code' => 'QR-008',
            ],
            [
                'work_order_no' => 'WO-2025-009',
                'batch_number' => '240125T1505',
                'selected' => true,
                'mes_batch_no' => 'BATCH-0009',
                'material_1_code' => 'MAT-090',
                'material_2_code' => 'INK-GRN',
                'material_3_code' => 'SUB-REC',
                'material_4_code' => null,
                'customer_part_number' => 'CP-1009',
                'production_due_date' => '2025-02-15',
                'quantity_to_produce' => 600,
                'quantity_produced' => 0,
                'forecast_quantity' => 700,
                'die_cut' => 'DC-220',
                'internal_remark' => 'Sustainability test batch.',
                'requested_delivery_date' => '2025-02-16',
                'no_of_colours' => 1,
                'sales_person_code' => 'SP-009',
                'order_date' => '2025-01-24',
                'production_date_completed' => null,
                'production_qty_completed' => 0,
                'qr_code' => 'QR-009',
            ],
            [
                'work_order_no' => 'WO-2025-010',
                'batch_number' => '280125T1230',
                'selected' => false,
                'mes_batch_no' => 'BATCH-0010',
                'material_1_code' => 'MAT-095',
                'material_2_code' => 'INK-CMYK',
                'material_3_code' => 'COAT-01',
                'material_4_code' => null,
                'customer_part_number' => 'CP-1010',
                'production_due_date' => '2025-02-20',
                'quantity_to_produce' => 2800,
                'quantity_produced' => 0,
                'forecast_quantity' => 3000,
                'die_cut' => 'DC-500',
                'internal_remark' => 'Seasonal cartons.',
                'requested_delivery_date' => '2025-02-22',
                'no_of_colours' => 5,
                'sales_person_code' => 'SP-010',
                'order_date' => '2025-01-28',
                'production_date_completed' => null,
                'production_qty_completed' => 0,
                'qr_code' => 'QR-010',
            ],
        ];

        foreach ($orders as $index => $order) {
            $templateRoute = $templateRoutes[$index % $templateRoutes->count()];
            $order['customer_id'] = $customerIds[$index % count($customerIds)];
            $order['template_route_id'] = $templateRoute->id;
            $customer = $customers->get($order['customer_id']);
            if ($customer) {
                $order['customer_code'] = $customer->customer_code;
                $order['customer_name'] = $customer->customer_name;
            }
            // persist template metadata snapshot on the work order
            $order['metadata'] = $templateRoute->metadata;
            WorkOrder::create($order);
        }
    }
}
