<?php

namespace Database\Seeders;

use App\Models\Customer;
use App\Models\WorkOrder;
use Illuminate\Database\Seeder;

class WorkOrderSampleSeeder extends Seeder
{
    public function run(): void
    {
        $workOrders = [
            [
                'work_order_no' => 'WB615487',
                'batch_number' => 'BATCH-001',
                'selected' => true,
                'mes_batch_no' => 'D271225T927',
                'customer_code' => 'P1283',
                'customer_name' => 'RESHEDA SIPET LTD',
                'material_1_code' => 'RPT351',
                'material_2_code' => null,
                'material_3_code' => null,
                'material_4_code' => null,
                'customer_part_number' => 'RSB4-RET/VC',
                'production_due_date' => '2025-12-18',
                'quantity_to_produce' => '432000',
                'quantity_produced' => '0',
                'forecast_quantity' => '0',
                'die_cut' => 'DC2558',
                'internal_remark' => null,
                'requested_delivery_date' => '2025-12-18',
                'no_of_colours' => '4',
                'sales_person_code' => 'JT',
                'order_date' => '2025-11-18',
                'production_date_completed' => null,
                'production_qty_completed' => '0',
            ],
            [
                'work_order_no' => 'WB615488',
                'batch_number' => 'BATCH-001',
                'selected' => true,
                'mes_batch_no' => 'D271225T927',
                'customer_code' => 'P1283',
                'customer_name' => 'DECTRON DICKINSON MEDICAL (S) PTE LTD',
                'material_1_code' => 'RPT351',
                'material_2_code' => null,
                'material_3_code' => null,
                'material_4_code' => null,
                'customer_part_number' => 'H2562',
                'production_due_date' => '2025-12-18',
                'quantity_to_produce' => '432000',
                'quantity_produced' => '0',
                'forecast_quantity' => '0',
                'die_cut' => 'DC2558',
                'internal_remark' => 'DYR : EUNIC / OAHIS',
                'requested_delivery_date' => '2025-12-18',
                'no_of_colours' => '4',
                'sales_person_code' => 'JT',
                'order_date' => '2025-11-18',
                'production_date_completed' => null,
                'production_qty_completed' => '0',
            ],
            [
                'work_order_no' => 'WB615489',
                'batch_number' => 'BATCH-001',
                'selected' => true,
                'mes_batch_no' => 'D271225T927',
                'customer_code' => 'P1284',
                'customer_name' => 'HQ TECHNOLOGY HOLDINGS PTE LTD',
                'material_1_code' => 'RPT351',
                'material_2_code' => null,
                'material_3_code' => null,
                'material_4_code' => null,
                'customer_part_number' => 'H2562',
                'production_due_date' => '2025-12-18',
                'quantity_to_produce' => '25000',
                'quantity_produced' => '0',
                'forecast_quantity' => '0',
                'die_cut' => 'DC2558',
                'internal_remark' => 'DYR : EUNIC / OAHIS',
                'requested_delivery_date' => '2025-12-18',
                'no_of_colours' => '4',
                'sales_person_code' => 'JT',
                'order_date' => '2025-11-18',
                'production_date_completed' => null,
                'production_qty_completed' => '0',
            ],
            [
                'work_order_no' => 'WB615490',
                'batch_number' => 'BATCH-001',
                'selected' => true,
                'mes_batch_no' => 'D271225T927',
                'customer_code' => 'Y2284',
                'customer_name' => 'VAT TECHNOLOGY SINGAPORE PTE LTD',
                'material_1_code' => 'AD281',
                'material_2_code' => 'L1551',
                'material_3_code' => 'XHX411',
                'material_4_code' => 'XHX412',
                'customer_part_number' => 'TT-3887-IRXBW/VC',
                'production_due_date' => '2025-12-18',
                'quantity_to_produce' => '53000',
                'quantity_produced' => '0',
                'forecast_quantity' => '0',
                'die_cut' => 'DC2554',
                'internal_remark' => 'ETA : 18/12/25',
                'requested_delivery_date' => '2025-12-18',
                'no_of_colours' => '4',
                'sales_person_code' => 'JT',
                'order_date' => '2025-11-18',
                'production_date_completed' => null,
                'production_qty_completed' => '0',
            ],
            [
                'work_order_no' => 'WB615491',
                'batch_number' => 'BATCH-001',
                'selected' => true,
                'mes_batch_no' => 'D271225T927',
                'customer_code' => 'Y2285',
                'customer_name' => 'CALIBRE PACKAGING SDN BHD',
                'material_1_code' => 'CCL-H111',
                'material_2_code' => null,
                'material_3_code' => null,
                'material_4_code' => null,
                'customer_part_number' => 'DHT-3887-IRXBW/VC',
                'production_due_date' => '2025-12-18',
                'quantity_to_produce' => '127500',
                'quantity_produced' => '0',
                'forecast_quantity' => '0',
                'die_cut' => 'DC2554',
                'internal_remark' => null,
                'requested_delivery_date' => '2025-12-18',
                'no_of_colours' => '4',
                'sales_person_code' => 'JT',
                'order_date' => '2025-11-18',
                'production_date_completed' => null,
                'production_qty_completed' => '0',
            ],
            [
                'work_order_no' => 'WB615492',
                'batch_number' => 'BATCH-001',
                'selected' => true,
                'mes_batch_no' => 'D271225T927',
                'customer_code' => 'T2831-PHI',
                'customer_name' => 'TECHNOLOGY SYSTEMS SDN BHD',
                'material_1_code' => 'TTS131',
                'material_2_code' => 'XHX300',
                'material_3_code' => 'YH102',
                'material_4_code' => 'XHX207',
                'customer_part_number' => 'PTS-CL-HT-H-85153',
                'production_due_date' => '2025-12-18',
                'quantity_to_produce' => '81500',
                'quantity_produced' => '0',
                'forecast_quantity' => '0',
                'die_cut' => 'DC2554',
                'internal_remark' => null,
                'requested_delivery_date' => '2025-12-18',
                'no_of_colours' => '4',
                'sales_person_code' => 'CL',
                'order_date' => '2025-11-18',
                'production_date_completed' => null,
                'production_qty_completed' => '0',
            ],
            [
                'work_order_no' => 'WB615493',
                'batch_number' => 'BATCH-001',
                'selected' => true,
                'mes_batch_no' => 'D271225T927',
                'customer_code' => 'T2831-PHI',
                'customer_name' => 'TECHNOLOGY SYSTEMS SDN BHD',
                'material_1_code' => 'AD283',
                'material_2_code' => null,
                'material_3_code' => null,
                'material_4_code' => null,
                'customer_part_number' => 'PRINTER LABEL',
                'production_due_date' => '2025-12-18',
                'quantity_to_produce' => '5000',
                'quantity_produced' => '0',
                'forecast_quantity' => '0',
                'die_cut' => 'DC2554',
                'internal_remark' => 'OC DEPT: PLEASE PROVIDE A REPORT',
                'requested_delivery_date' => '2025-12-18',
                'no_of_colours' => '4',
                'sales_person_code' => 'CL',
                'order_date' => '2025-11-18',
                'production_date_completed' => null,
                'production_qty_completed' => '0',
            ],
            [
                'work_order_no' => 'WB615494',
                'batch_number' => 'BATCH-001',
                'selected' => true,
                'mes_batch_no' => 'D271225T927',
                'customer_code' => 'P2831',
                'customer_name' => 'DESTWORLD LIFESTYLE PTE LTD',
                'material_1_code' => 'LH281',
                'material_2_code' => null,
                'material_3_code' => null,
                'material_4_code' => null,
                'customer_part_number' => 'ISM-1155',
                'production_due_date' => '2025-12-18',
                'quantity_to_produce' => '8000',
                'quantity_produced' => '0',
                'forecast_quantity' => '0',
                'die_cut' => 'DC2848',
                'internal_remark' => null,
                'requested_delivery_date' => '2025-12-18',
                'no_of_colours' => '4',
                'sales_person_code' => 'CL',
                'order_date' => '2025-11-18',
                'production_date_completed' => null,
                'production_qty_completed' => '0',
            ],
            [
                'work_order_no' => 'WB615495',
                'batch_number' => 'BATCH-001',
                'selected' => true,
                'mes_batch_no' => 'D271225T927',
                'customer_code' => 'T2835',
                'customer_name' => 'TURCHEE PRECISION ENGINEERING PTE LTD',
                'material_1_code' => 'YH135',
                'material_2_code' => null,
                'material_3_code' => null,
                'material_4_code' => null,
                'customer_part_number' => 'ISM-1155',
                'production_due_date' => '2025-12-18',
                'quantity_to_produce' => '5000',
                'quantity_produced' => '0',
                'forecast_quantity' => '0',
                'die_cut' => 'DC2848',
                'internal_remark' => null,
                'requested_delivery_date' => '2025-12-18',
                'no_of_colours' => '4',
                'sales_person_code' => 'CL',
                'order_date' => '2025-11-18',
                'production_date_completed' => null,
                'production_qty_completed' => '0',
            ],
            [
                'work_order_no' => 'WB615496',
                'batch_number' => 'BATCH-001',
                'selected' => true,
                'mes_batch_no' => 'D271225T927',
                'customer_code' => 'H3165',
                'customer_name' => 'HIKRON SEMICONDUCTOR ASIA OPERATIONS PTE LTD',
                'material_1_code' => 'AD283',
                'material_2_code' => null,
                'material_3_code' => null,
                'material_4_code' => null,
                'customer_part_number' => 'ISM-1157',
                'production_due_date' => '2025-12-18',
                'quantity_to_produce' => '3000',
                'quantity_produced' => '0',
                'forecast_quantity' => '0',
                'die_cut' => 'DC2839',
                'internal_remark' => null,
                'requested_delivery_date' => '2025-12-18',
                'no_of_colours' => '4',
                'sales_person_code' => 'CL',
                'order_date' => '2025-11-18',
                'production_date_completed' => null,
                'production_qty_completed' => '0',
            ],
            [
                'work_order_no' => 'WB615497',
                'batch_number' => 'BATCH-001',
                'selected' => true,
                'mes_batch_no' => 'D271225T927',
                'customer_code' => 'H3167',
                'customer_name' => 'FLEXTRONICS SHAH ALAM SDN BHD',
                'material_1_code' => 'AD283',
                'material_2_code' => null,
                'material_3_code' => null,
                'material_4_code' => null,
                'customer_part_number' => 'WATANAH-471226-H01',
                'production_due_date' => '2025-12-18',
                'quantity_to_produce' => '3000',
                'quantity_produced' => '0',
                'forecast_quantity' => '0',
                'die_cut' => 'DC2839',
                'internal_remark' => null,
                'requested_delivery_date' => '2025-12-18',
                'no_of_colours' => '4',
                'sales_person_code' => 'PER',
                'order_date' => '2025-11-18',
                'production_date_completed' => null,
                'production_qty_completed' => '0',
            ],
        ];

        foreach ($workOrders as $workOrder) {
            $customer = Customer::firstOrCreate(
                ['customer_code' => $workOrder['customer_code']],
                [
                    'customer_name' => $workOrder['customer_name'],
                    'status' => 'active',
                ]
            );

            WorkOrder::updateOrCreate(
                ['work_order_no' => $workOrder['work_order_no']],
                array_merge($workOrder, [
                    'customer_id' => $customer->id,
                    'template_route_id' => null,
                    'metadata' => null,
                ])
            );
        }
    }
}
