name: FTP Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ftp.ccldesignmes.com
          port: 21
          username: u768061773.mesapp
          password: Superadmin143!
          local-dir: './'
          server-dir: '/'
          dangerous-clean-slate: true
          exclude: |
            **/.env
            **/vendor/**
            **/node_modules/**
